name = "MCIntegrals"
uuid = "59f6df4c-24ce-11e9-2924-b5225c0d4fed"
authors = ["Jan Weidner <jw3126@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
